name: Create DeviceOfHermes draft

on:
  push:
    tags:
      - "DeviceOfHermes_*"

permissions:
  contents: write

jobs:
  create-draft:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Constant name
        run: echo "VERSION=${GITHUB_REF_NAME#DeviceOfHermes_}" >> $GITHUB_ENV

      - name: Create Draft
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: DeviceOfHermes ${{ env.VERSION }}
          body_path: ./DeviceOfHermes/Release.md
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
